/* ==========================================================================
   BANK MANDIRI REGION V - MASTER BLANK SPOT & UMKM DATABASE
   Synced with Google Sheet ID: 1Jk8IbeIjTyQF-97DYDMunvppcAELrwLeczjgCQwj1J8
   ========================================================================== */

window.MASTER_BLANKSPOTS_UMKM_DATA = [
  {
    "no": 1,
    "namaKawasan": "Kecamatan Sukaraja",
    "namaLengkap": "Kecamatan Sukaraja, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Sentul City 1",
    "alamatUnitTerdekat": "Jl. MH Thamrin Kav. 8 Sentul City",
    "jarakKm": 0.6,
    "lat": -6.568166,
    "lng": 106.840557,
    "prioritasExpansion": "-",
    "jumlahUMKM": 2793
  },
  {
    "no": 2,
    "namaKawasan": "Kecamatan Sawangan",
    "namaLengkap": "Kecamatan Sawangan, Kota Depok",
    "wilayah": "Kota Depok",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Galeria Sawangan 1",
    "alamatUnitTerdekat": "Jl. Meruyung Raya No. 60 RT 05 RW 10",
    "jarakKm": 1.4,
    "lat": -6.406149,
    "lng": 106.767412,
    "prioritasExpansion": "-",
    "jumlahUMKM": 166
  },
  {
    "no": 3,
    "namaKawasan": "Kecamatan Limo",
    "namaLengkap": "Kecamatan Limo, Kota Depok",
    "wilayah": "Kota Depok",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Depok Cinere Limo 1",
    "alamatUnitTerdekat": "Jl. Cinere Blok F1 No. 7, Cinere",
    "jarakKm": 2.5,
    "lat": -6.365939,
    "lng": 106.779014,
    "prioritasExpansion": "-",
    "jumlahUMKM": 140
  },
  {
    "no": 4,
    "namaKawasan": "Kecamatan Megamendung",
    "namaLengkap": "Kecamatan Megamendung, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Cisarua 1",
    "alamatUnitTerdekat": "Jl. Raya Cisarua Km.80 No.28 Kp. Pasanggrahan RT.02/01",
    "jarakKm": 2.9,
    "lat": -6.667128,
    "lng": 106.905069,
    "prioritasExpansion": "-",
    "jumlahUMKM": 163
  },
  {
    "no": 5,
    "namaKawasan": "Kecamatan Tajurhalang",
    "namaLengkap": "Kecamatan Tajurhalang, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Kemang 1",
    "alamatUnitTerdekat": "Jl. Raya Bogor RT 003 RW 008",
    "jarakKm": 2.9,
    "lat": -6.470783,
    "lng": 106.756132,
    "prioritasExpansion": "-",
    "jumlahUMKM": 1439
  },
  {
    "no": 6,
    "namaKawasan": "Kecamatan Cibungbulang",
    "namaLengkap": "Kecamatan Cibungbulang, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Leuwiliang 1",
    "alamatUnitTerdekat": "JL. Raya Leuwiliang No. 11 RT 001 RW 012",
    "jarakKm": 3.8,
    "lat": -6.577466,
    "lng": 106.663986,
    "prioritasExpansion": "-",
    "jumlahUMKM": 613
  },
  {
    "no": 7,
    "namaKawasan": "Kecamatan Ranca Bungur",
    "namaLengkap": "Kecamatan Ranca Bungur, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Dramaga 1",
    "alamatUnitTerdekat": "Jl. Raya Cibanteng No.150 RT 05 RW 03",
    "jarakKm": 4.6,
    "lat": -6.518021,
    "lng": 106.711364,
    "prioritasExpansion": "-",
    "jumlahUMKM": 1693
  },
  {
    "no": 8,
    "namaKawasan": "Kecamatan Leuwisadeng",
    "namaLengkap": "Kecamatan Leuwisadeng, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Leuwiliang 1",
    "alamatUnitTerdekat": "JL. Raya Leuwiliang No. 11 RT 001 RW 012",
    "jarakKm": 5.2,
    "lat": -6.571286,
    "lng": 106.582495,
    "prioritasExpansion": "-",
    "jumlahUMKM": 204
  },
  {
    "no": 9,
    "namaKawasan": "Kecamatan Ciawi",
    "namaLengkap": "Kecamatan Ciawi, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Cisarua 1",
    "alamatUnitTerdekat": "Jl. Raya Cisarua Km.80 No.28 Kp. Pasanggrahan RT.02/01",
    "jarakKm": 6.0,
    "lat": -6.691952,
    "lng": 106.877287,
    "prioritasExpansion": "-",
    "jumlahUMKM": 926
  },
  {
    "no": 10,
    "namaKawasan": "Kecamatan Tamansari",
    "namaLengkap": "Kecamatan Tamansari, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Ciomas 1",
    "alamatUnitTerdekat": "Grand Eng 21, RT.02 RW.11",
    "jarakKm": 6.0,
    "lat": -6.647745,
    "lng": 106.744407,
    "prioritasExpansion": "-",
    "jumlahUMKM": 674
  },
  {
    "no": 11,
    "namaKawasan": "Kecamatan Caringin",
    "namaLengkap": "Kecamatan Caringin, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Cigombong 1",
    "alamatUnitTerdekat": "Ruko Plaza Lido 26-27, Jl Mayjend H.E. Sukma Km 23, Perumahan Villa Mutiara Lido, Kel/Kec Cigombong",
    "jarakKm": 6.2,
    "lat": -6.728433,
    "lng": 106.853487,
    "prioritasExpansion": "-",
    "jumlahUMKM": 537
  },
  {
    "no": 12,
    "namaKawasan": "Kecamatan Jonggol",
    "namaLengkap": "Kecamatan Jonggol, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Jonggol 1",
    "alamatUnitTerdekat": "Ruko Citra Indah Square Blok RCS-02 No. 2, Jl. Raya Jonggol KM 23,2",
    "jarakKm": 6.3,
    "lat": -6.492498,
    "lng": 107.053230,
    "prioritasExpansion": "-",
    "jumlahUMKM": 1227
  },
  {
    "no": 13,
    "namaKawasan": "Kecamatan Cijeruk",
    "namaLengkap": "Kecamatan Cijeruk, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Tajur 1",
    "alamatUnitTerdekat": "Jl. Raya Tajur No. 121 B & C",
    "jarakKm": 6.4,
    "lat": -6.679587,
    "lng": 106.791741,
    "prioritasExpansion": "-",
    "jumlahUMKM": 765
  },
  {
    "no": 14,
    "namaKawasan": "Kecamatan Ciseeng",
    "namaLengkap": "Kecamatan Ciseeng, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor ATC Parung 1",
    "alamatUnitTerdekat": "Ruko ATC Parung, Blok A6-A7, Jl. Raya Parung, No. 6",
    "jarakKm": 6.9,
    "lat": -6.468108,
    "lng": 106.685975,
    "prioritasExpansion": "-",
    "jumlahUMKM": 464
  },
  {
    "no": 15,
    "namaKawasan": "Kecamatan Tenjolaya",
    "namaLengkap": "Kecamatan Tenjolaya, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Ciomas 1",
    "alamatUnitTerdekat": "Grand Eng 21, RT.02 RW.11",
    "jarakKm": 8.8,
    "lat": -6.643899,
    "lng": 106.705814,
    "prioritasExpansion": "-",
    "jumlahUMKM": 817
  },
  {
    "no": 16,
    "namaKawasan": "Kecamatan Rumpin",
    "namaLengkap": "Kecamatan Rumpin, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Gunung Sindur 1",
    "alamatUnitTerdekat": "Jl. Pemuda No. 38, RT 002 RW 001",
    "jarakKm": 10.4,
    "lat": -6.452694,
    "lng": 106.622543,
    "prioritasExpansion": "-",
    "jumlahUMKM": 1007
  },
  {
    "no": 17,
    "namaKawasan": "Kecamatan Pamijahan",
    "namaLengkap": "Kecamatan Pamijahan, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Leuwiliang 1",
    "alamatUnitTerdekat": "JL. Raya Leuwiliang No. 11 RT 001 RW 012",
    "jarakKm": 11.8,
    "lat": -6.676927,
    "lng": 106.652234,
    "prioritasExpansion": "-",
    "jumlahUMKM": 3036
  },
  {
    "no": 18,
    "namaKawasan": "Kecamatan Nanggung",
    "namaLengkap": "Kecamatan Nanggung, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Leuwiliang 1",
    "alamatUnitTerdekat": "JL. Raya Leuwiliang No. 11 RT 001 RW 012",
    "jarakKm": 12.1,
    "lat": -6.636019,
    "lng": 106.540430,
    "prioritasExpansion": "-",
    "jumlahUMKM": 243
  },
  {
    "no": 19,
    "namaKawasan": "Kecamatan Cariu",
    "namaLengkap": "Kecamatan Cariu, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Jonggol 1",
    "alamatUnitTerdekat": "Ruko Citra Indah Square Blok RCS-02 No. 2, Jl. Raya Jonggol KM 23,2",
    "jarakKm": 12.6,
    "lat": -6.514130,
    "lng": 107.134157,
    "prioritasExpansion": "-",
    "jumlahUMKM": 461
  },
  {
    "no": 20,
    "namaKawasan": "Kecamatan Cigudeg",
    "namaLengkap": "Kecamatan Cigudeg, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Leuwiliang 1",
    "alamatUnitTerdekat": "JL. Raya Leuwiliang No. 11 RT 001 RW 012",
    "jarakKm": 12.6,
    "lat": -6.497373,
    "lng": 106.544163,
    "prioritasExpansion": "-",
    "jumlahUMKM": 383
  },
  {
    "no": 21,
    "namaKawasan": "Kecamatan Sukamakmur",
    "namaLengkap": "Kecamatan Sukamakmur, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Cisarua 1",
    "alamatUnitTerdekat": "Jl. Raya Cisarua Km.80 No.28 Kp. Pasanggrahan RT.02/01",
    "jarakKm": 14.1,
    "lat": -6.582503,
    "lng": 107.014197,
    "prioritasExpansion": "-",
    "jumlahUMKM": 423
  },
  {
    "no": 22,
    "namaKawasan": "Kecamatan Parung Panjang",
    "namaLengkap": "Kecamatan Parung Panjang, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Gunung Sindur 1",
    "alamatUnitTerdekat": "Jl. Pemuda No. 38, RT 002 RW 001",
    "jarakKm": 14.8,
    "lat": -6.367633,
    "lng": 106.552643,
    "prioritasExpansion": "-",
    "jumlahUMKM": 433
  },
  {
    "no": 23,
    "namaKawasan": "Kecamatan Sukajaya",
    "namaLengkap": "Kecamatan Sukajaya, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Leuwiliang 1",
    "alamatUnitTerdekat": "JL. Raya Leuwiliang No. 11 RT 001 RW 012",
    "jarakKm": 17.0,
    "lat": -6.622747,
    "lng": 106.484521,
    "prioritasExpansion": "-",
    "jumlahUMKM": 272
  },
  {
    "no": 24,
    "namaKawasan": "Kecamatan Tanjungsari",
    "namaLengkap": "Kecamatan Tanjungsari, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Jonggol 1",
    "alamatUnitTerdekat": "Ruko Citra Indah Square Blok RCS-02 No. 2, Jl. Raya Jonggol KM 23,2",
    "jarakKm": 21.8,
    "lat": -6.613549,
    "lng": 107.135090,
    "prioritasExpansion": "-",
    "jumlahUMKM": 476
  },
  {
    "no": 25,
    "namaKawasan": "Kecamatan Tenjo",
    "namaLengkap": "Kecamatan Tenjo, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Bogor Gunung Sindur 1",
    "alamatUnitTerdekat": "Jl. Pemuda No. 38, RT 002 RW 001",
    "jarakKm": 22.3,
    "lat": -6.376277,
    "lng": 106.484681,
    "prioritasExpansion": "-",
    "jumlahUMKM": 648
  },
  {
    "no": 26,
    "namaKawasan": "Kecamatan Jasinga",
    "namaLengkap": "Kecamatan Jasinga, Kabupaten Bogor",
    "wilayah": "Kabupaten Bogor",
    "statusCoverage": "Blank Spot (0 Cabang)",
    "jumlahUnit": 0,
    "unitTerdekat": "Leuwiliang 1",
    "alamatUnitTerdekat": "JL. Raya Leuwiliang No. 11 RT 001 RW 012",
    "jarakKm": 22.5,
    "lat": -6.467354,
    "lng": 106.456273,
    "prioritasExpansion": "-",
    "jumlahUMKM": 454
  }
];
